# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: kaban584
    volumes:
      - postgre_volume:/data/postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
            PGADMIN_DEFAULT_EMAIL: dr.leonixx@yandex.ru
            PGADMIN_DEFAULT_PASSWORD: qwe123
            PGADMIN_LISTEN_PORT: 80
    ports:
      - 8081:80
volumes:
  postgre_volume:
